name: "Detect language and run scan"

on: 
  workflow_dispatch:
jobs:
  detect-languages:
    runs-on: ubuntu-latest
    outputs:
      langs: ${{ steps.setlangs.outputs.langs }}
    steps:
      - uses: actions/checkout@v4
      - id: setlangs
        run: |
          # Example: detect by file extensions
            langs=()

            if ls -1 **/*.cs 1> /dev/null 2>&1; then langs+=("csharp"); fi
            if ls -1 **/*.java 1> /dev/null 2>&1; then langs+=("java"); fi
            if ls -1 **/*.js 1> /dev/null 2>&1; then langs+=("javascript"); fi
            if ls -1 **/*.py 1> /dev/null 2>&1; then langs+=("python"); fi
            if ls -1 **/*.cpp 1> /dev/null 2>&1; then langs+=("cpp"); fi

          # Convert bash array -> JSON
          json=$(printf '%s\n' "${langs[@]}" | jq -R . | jq -s .)
          echo "langs=$json" >> $GITHUB_OUTPUT

  codeql:
    needs: detect-languages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ fromJSON(needs.detect-languages.outputs.langs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v3
