name: "Detect language and run scan"

on: 
  workflow_dispatch:
jobs:
  detect-languages:
    runs-on: ubuntu-latest
    outputs:
      langs: ${{ steps.setlangs.outputs.langs }}
    steps:
      - uses: actions/checkout@v4
      - id: setlangs
        run: |
          # Example: detect by file extensions
            langs=()
            shopt -s globstar

            if find . -name "*.js" | grep -q .; then langs+=("javascript"); fi
            if find . -name "*.py" | grep -q .; then langs+=("python"); fi
            if find . -name "*.cs" | grep -q .; then langs+=("csharp"); fi
            if find . -name "*.java" | grep -q .; then langs+=("java"); fi
            if find . -name "*.cpp" | grep -q .; then langs+=("cpp"); fi

          # Convert bash array -> JSON
          json=$(printf '%s\n' "${langs[@]}" | jq -R . | jq -s -c .)
          echo "$json" >> $GITHUB_OUTPUT

  codeql:
    needs: detect-languages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ fromJSON(needs.detect-languages.outputs.langs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v3
